### PR TITLE
BasicGates katas add clarification about endiannes and qubit order.

### PR DESCRIPTION
**Pull request by bpatra**
After finishing `MultiQubitSystems` and `MultiQubitGates` tutorials and tackling Part II of `Basic Gates` kata, I thought the little-endian notation would be de-facto notation for all katas. For instance this is the notation used in the `DumpMachine` instruction.

I believe that mentioning big-endian is the notation used in this kata could be useful and avoid some confusion from learners.

### CODE REVIEW

**Comment by bpatra** [comment]
You are right, your correction is absolutely what I wanted to express. I'll make the changes.

**Comment by bpatra** [comment]
Actually, I realized that in Basic Gates katas  Test outputs do not print qubit with little-endian notation at al. Therefore, I rewrote without mentioning endianness at all, I hope this will avoid confusing for the newcomers like me.

I reused a similar sentence than the one that is mentioned in [Measurement kata](https://github.com/microsoft/QuantumKatas/blob/master/Measurements/Measurements.ipynb#Task-1.6.-Distinguish-four-basis-states.)

> In this task and the subsequent ones the order of qubit states in task description matches the order of qubits in the array (i.e.,  |10⟩  state corresponds to qs[0] in state  |1⟩  and qs[1] in state  |0⟩ ).

**Comment by tcNickolas** [comment]
If we run task 2.1, we'll get the following output:

image

The task promises a superposition of basis states 00 and 10, and the test prints a state with non-zero amplitudes of 0 and 1, so is seems there is some space for confusion?

(I'm happy to merge your note in its current state, but want to get to the root of the the doubts you had)

**Comment by bpatra** [comment]
Ah ok I got a different output (see code below). I made my fix on an outdated version and then rebased for PR. My bad.

Screenshot 2020-04-13 at 16 45 50

I'll PR again.

**Comment by bpatra** [comment]
@tcNickolas hope that 254c145 is finally what we wanted 😅

**Pull request merged**
