### PR TITLE
Ripple Carry Addition kata

### PR DESCRIPTION
**Pull request by fafel**
RCA Kata

### CODE REVIEW

**Comment by tcNickolas** [comment]
And could you please sign the CLA?

**Comment by tcNickolas** [comment]
A gentle ping with respect to signing the CLA :-) 
I'm happy to finish the testing framework, but we won't be able to use your contribution at all if you don't sign the CLA, and that would be a shame, since the tasks look great.

**Comment by fafel** [comment]
Hi Mariia,

Im sorry this got burried before I got to it. Do you know where exactly I need to go to sign the CLA? Im looking through my emails and cant seem to find it. Phillip said theres a web form somewhere?

Thanks,
Max



Get Outlook for Android<https://aka.ms/ghei36>

**Comment by tcNickolas** [comment]
No worries, I know exactly how things can get buried sometimes :-)

I think the link is https://cla.opensource.microsoft.com/Microsoft/QuantumKatas?pullRequest=84 - it's in [this comment](https://github.com/Microsoft/QuantumKatas/pull/84#issuecomment-475432863) by CLA bot.

**Comment by tcNickolas** [comment]
Did that link work for you?

**Comment by tcNickolas** [comment]
A gentle ping :-)

**Comment by tcNickolas** [comment]
@fafel If signing CLA is problematic for you for some reason (not related to the willingness to contribute this kata to our project), an alternate way to do it would be for me to take your code, do the necessary fixes in the testing framework and open a new PR with you marked as a co-author, similar to other PRs with multiple authors (for example, [this one](https://github.com/microsoft/QuantumKatas/pull/87)).

Please let me know how you'd like to proceed. I'd really like to get this going, since the kata looks good!

**Comment by tcNickolas** [comment]
@fafel We need to reach some conclusion on what we're doing with this kata. Please let me know if you're going to sign the CLA by July 15th. If I don't hear back from you by that time, I'll have to regretfully close this pull request to enable other people to work on this topic.

**Comment by fafel** [comment]
Hi Mariia,

So sorry, I have been out of the country and off my email. I don't plan to sign the CLA but I am still happy to let you use the code with any modifications that are needed. I hope this resolves this for you, so sorry again for the delay.

Thanks,
Max

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tcNickolas** [comment]
Thank you for letting me know! I'll take the second approach then, do modifications and create a new PR marking you as a co-author.

**Comment by tcNickolas** [comment]
Closing this pull request, since we will not continue working on it.

**Pull request closed without merging**
