### PR TITLE
New kata on hierarchical reversible synthesis

### PR DESCRIPTION
**Pull request by lana555**
Hello, 

as part of a course project, I have developed a kata which explains hierarchical reversible synthesis. I'd like to add the kata to the existing collection of katas.

The kata consists out of 4 tasks. The first two are basic examples of reversible circuits (i.e., circuits implementing 2-input XOR and AND functions). Task 3 requires designing a 3-input majority function as a reversible circuit and, in Task 4, the user develops an optimized version of the same function (i.e., with a smaller number of gates and ancillas).

Please let me know if you have any comments or questions. 

Thanks!

### CODE REVIEW

**Comment by tcNickolas** [comment]
It's exciting to see that kind of projects in courses not taught by our team! Out of curiosity, would you mind sharing at what university was this course taught?

Reversible synthesis is a very promising topic for a kata-style tutorial, but these tasks seem to be a bit too few for a full kata (the only other kata as short is SuperdenseCoding, and that protocol is just that short). Also, they have all been covered in other katas: XOR and AND in [SolveSATWithGrover](https://github.com/Microsoft/QuantumKatas/blob/master/SolveSATWithGrover/Tasks.qs), majority function in the [Deutsch-Jozsa algorithm](https://github.com/Microsoft/QuantumKatas/blob/master/DeutschJozsaAlgorithm/Tasks.qs). I'm not sure it's a great idea to have a separate kata with duplicate tasks only... :-( 

Do you have ideas for more tasks that could teach the learner further concepts of reversible synthesis and make this kata more interesting?

**Comment by lana555** [comment]
Thank you for your feedback! I will think about how to extend the kata and get back to you soon. If you will have any suggestions on possible extensions in the meantime, please let me know.

The project was done as part of a doctoral course '[Advanced logic synthesis and quantum computing](http://isa.epfl.ch/imoniteur_ISAP/!itffichecours.htm?ww_i_matiere=2405848449&ww_x_anneeAcad=2018-2019&ww_i_section=2139068&ww_i_niveau=&ww_c_langue=en)' at EPFL, given by Mathias Soeken.

**Comment by tcNickolas** [comment]
Sorry for the delay replying, I had to look into the papers you referenced to figure out possible directions for this kata.

The tasks currently presented in the kata are building blocks for reversible synthesis and one example of a synthesis task. To extend them into an interesting kata, I would consider what are the increasingly complex examples of circuits that can be implemented using reversible synthesis, and ask the learner to implement them. Those examples have to showcase certain tricks and properties used in synthesis algorithms.

For example, if you want to follow the "Hierarchical Reversible Logic Synthesis Using LUTs" paper, you could explore building circuits from logic networks - given a fixed logic network, implement it as a circuit using at most X ancillas (you can limit the total number of qubits allocated by a task using `CounterSimulator`). With a reasonable set of tasks and restrictions on their implementation you could teach straightforward translation of LUT into a circuit (with 1 ancilla per node), translation with uncomputation, ancilla reuse etc. You would not go all the way up to the algorithm from section 4 (implementing data structures in Q# is not trivial), but you could teach to do manually a lot of pieces that go into it, the logic on which it is built.

For the other paper I imagine you could do a similar level of exploration - I have not spent enough time on it to suggest specific tasks, but they would involve generation of circuits that correspond to the given permutations, from the simplest permutations like identity and NOT to more complicated ones which require a lot of gates.

These directions seem quite different (and I'm sure there are a couple of other directions in which you could evolve this kata). Please let me know if you plan to continue working on any of these topics!

**Comment by msoeken** [comment]
I have some ideas how to extend this Kata, but am quite restricted in time these days. I can contribute some examples based on the LUT-based hierarchical synthesis around beginning of November.

**Comment by tcNickolas** [comment]
Thank you, that would be fantastic!

**Comment by tcNickolas** [comment]
This kata requires a lot of work to complete, and it doesn't look like we'll get to it any time soon. I will regretfully close this PR and bear in mind that at some point we'd love to expand our materials on reversible synthesis. @lana555 Thank you again for your effort, and please let us know if you'd like to keep working on it!

**Pull request closed without merging**
