### PR TITLE
Task 1-4 from MS, Task 1.5 Me, V2

### PR DESCRIPTION
**Pull request by TonyHoldroyd**
Task 1-4 from MS, Task 1.5 Me, V2
Cooruption fixed.
all done in Jupyter NB

### CODE REVIEW

**Review by tcNickolas — APPROVED** [review]
Apologies for the delay reviewing this - between the conference in October and some urgent non-opensource work after that today's the first day I can take a look at the open source again!

This looks good (I'm glad you've figured out the conflicts and corruptions you've been fighting!) - I did a round of cleanup and added the links from the kata to the solutions of tasks 1.5-1.7. I removed the explanations of global phase and how it doesn't affect the outcomes of measurements in the last two tasks and replaced them with links to relevant tutorials - I felt that explaining the effect of the global phase on measurements by taking a product of the state with itself would just confuse the reader, since the product needs to be taken with the states in the measurement basis. I kept the explained example of calculating the global phase, though - it's a good idea, I know I never like to do that computation with complex phases so it's essential :-)

Thank you so much for working on this!!

**Comment by TonyHoldroyd** [comment]
Thank you very much for your feedback Mariia,  I have the next 3 tasks
ready for your perusal and I will append them to your edit of the tasks so
far and issue a new pull request soon.

**Comment by TonyHoldroyd** [comment]
Ciao Mariia, I was wondering if you use nbextensions with your Notebooks,
in particular I was going to install a spellchecker for my markdow.n, but
Iafet my awful experience with Lab, I don't want to do anything to endanger
my installation. Thanks

**Comment by tcNickolas** [comment]
No, I don't use any extra extensions, just the raw "jupyter notebook" command which runs the notebook in the browser. For a spellcheck, I usually open the notebook in Visual Studio - it treats it as a JSON file and happily finds typos.

**Comment by TonyHoldroyd** [comment]
Thanks, I'll do the same

**Pull request merged**
