### PR TITLE
Remove _Test suffixes

### LINKED ISSUE #532: Remove _Test suffix from Q# test names
Now that we have switched to using `@Test` attribute (#478), we are not using `_Test` suffix in operation names to identify tests any longer. We should be able to remove that suffix from all Q# tests. 

Each test is defined in `Tests.qs` file of the corresponding kata/tutorial, and mentioned in the `%kata` cells of the Jupyter notebook frontend of the kata and the matching workbook, if it exists, so the changes should modify these files simultaneously.

### PR DESCRIPTION
**Pull request by PiotrBlachnio**
Fixes #532

### CODE REVIEW

**Comment by vivanwin** [comment]
Hi @PiotrBlachnio,

Thank you for your first PR!

Looking at the CI build it looks like there is currently a same name in the `teleportation/task.qs`. Would you be able to change this?

**Comment by PiotrBlachnio** [comment]
There are many name conflicts in files due to duplicates:
- tutorials/ComplexArithmetic/testing.py
- tutorials/LinearAlgebra/testing.py

Should I rename the tests? If so, how should I name them? Otherwise, I can just leave _test suffix.

**Comment by vivanwin** [comment]
Hi @PiotrBlachnio,

The python tests have not been update in #532, so these can remain unchanged.

**Comment by PiotrBlachnio** [comment]
Suffixes have been removed from all files except:
- tutorials/ComplexArithmetic/testing.py
- tutorials/LinearAlgebra/testing.py
- Teleportation/Tasks.qs

**Review by vivanwin — APPROVED** [review]
This looks good. Thank you for your help!

**Pull request merged**
