### PR TITLE
Updated the QDK version to 0.18.2108.160999

### PR DESCRIPTION
**Pull request by kuzminrobin**

### CODE REVIEW

**Comment by tcNickolas** [comment]
I'm trying the update on Binder, and it doesn't seem to work - for https://mybinder.org/v2/gh/Microsoft/QuantumKatas/kuzminrobin/hotfix.0.18.2108.160999?filepath=index.ipynb, the image builds successfully but when I try to execute a cell, it waits a minute or two and then says "kernel died". It might be that I'm getting bad machines, but I haven't seen this before, so it worries me

**Comment by kuzminrobin** [comment]
@tcNickolas, I clicked your link, this opened "Quantum Katas and Tutorials as Jupyter Notebooks", then I clicked ["Complex arithmetic (tutorial)"](https://notebooks.gesis.org/binder/jupyter/user/microsoft-quantumkatas-808addjo/notebooks/tutorials/ComplexArithmetic/ComplexArithmetic.ipynb), executed couple of first cells and got "Success!" for both.
Do I miss anything?

**Comment by tcNickolas** [comment]
ComplexArithmetic is a Python tutorial, so it's not really representative of the IQ# version. We usually use Measurements tutorial for the simple checks. 

I'm still getting dead kernel with the new version if the URL starts with hub-binder.mybinder.ovh, but I got a working variant once with URL starting with notebooks.gesis.org. I wonder if Binder did something funny with their settings...

**Comment by kuzminrobin** [comment]
Confirmed. I observe the same behavior.

I replaced in your URL (@tcNickolas) the fragment `kuzminrobin/hotfix.0.18.2108.160999` with fragment `main`. Got this URL: https://mybinder.org/v2/gh/Microsoft/QuantumKatas/main?filepath=index.ipynb 
When I open it, it always is opened on a server `hub.gke2.mybinder.org` (3 times in a row) and in the Measurements page the first 2 cells succeed.

If I click [_your_ URL](https://mybinder.org/v2/gh/Microsoft/QuantumKatas/kuzminrobin/hotfix.0.18.2108.160999?filepath=index.ipynb) then I observe the same behavior as you do. 
If it is opened on the server notebooks.gesis.org then success. I only got this server 1 time.
If it is opened on the server hub-binder.mybinder.ovh (about 7 times in a row) then in the Measurements page the first cell causes the kernel to die. And even the manual restart of the kernel does not help. There was a time when even the server failed to start normally.

Looks like a server problem of the hub-binder.mybinder.ovh.
@cgranade, @guenp, @tcNickolas, what should I do in this situation? Please advise.

**Comment by tcNickolas** [comment]
I would check with myBinder maintainers at https://gitter.im/jupyterhub/binder to find out what are the differences between these URLs and the underlying VMs, and what's the logic they use to choose between them (I never could get the faulty ones for the main branch of the Katas to check whether that exhibits the same problem). If they say that the ones we're having trouble with are just a bad batch, and are not assigned to main branches, I'd say go ahead and merge. If the VMs at different URLs have different settings but are supposed to be otherwise healthy, this might mean there is some issue with IQ# that manifests only on those settings.

(I'd follow up with them myself, but I'm going offline for a couple of days, so I won't be able to do that until Tuesday)

**Comment by cgranade** [comment]
For clarification, mybinder.org is a front-end to several different BinderHub instances contributed to the NumFOCUS project, of including both gke.mybinder.org and hub-binder.mybinder.ovh. Each BinderHub instance caches a single Docker image for each commit of the underlying repository. Thus, for each commit on this repo, one image gets cached on _each_ different BinderHub instance pointed to by mybinder.org. If a particular instance ran into a problem building the image that didn't result in the image build failing, that corrupt image will be cached until a new commit on this repo invalidates the cache.

(BTW, this is why the samples repository pre-builds images and then points to those from ★binder — allows us to share cached images across all BinderHub instances used by mybinder.org. Happy to share more details about that infrastructure if it would be helpful.)

In any case, if this persists, the mybinder.org team at NumFOCUS is quite responsive both on GitHub and on Twitter, such that I'd suggest reaching out to ask.

**Comment by kuzminrobin** [comment]
Chris' reply makes me believe that with the current commit in my branch, some wrong/corrupt build could be produced and cached for `hub-binder.mybinder.ovh`. To recover from that I will try to make one more commit with some insignificant/fake change. If the problem persists, then I'll discuss that with myBinder maintainers.

**Comment by kuzminrobin** [comment]
I made a fake change commit and clicked https://mybinder.org/v2/gh/Microsoft/QuantumKatas/kuzminrobin/hotfix.0.18.2108.160999?filepath=index.ipynb
The image build has started. In the log I have seen the errors/failures, see below (see full raw log in the internal discussion, I fail to find a way to attach it in GitHub). 

It took about 50 minutes to observe the log, and another 20 minutes the log has been hanging after the last line "Successfully pushed" (the notebook has never been opened).

**Looks like there are errors on our side. Any help is welcome.**

Repeated click on the link above opened the notebook (on the server `hub-binder.mybinder.ovh`). Where the execution of the first cell in the Measurements notebook has killed the kernel. The same happened with the Deutsch–Jozsa algorithm notebook (again on `hub-binder.mybinder.ovh`). And I expect the same with any notebook where the failures listed below happened.

---
[NbConvertApp] Converting notebook Measurements/Measurements.ipynb to markdown
**fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS6307 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Not all code paths return a value.**
(Multiple identical failures)

---
[NbConvertApp] Converting notebook DeutschJozsaAlgorithm/DeutschJozsaAlgorithm.ipynb to markdown
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS6307 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Not all code paths return a value.
      
---
[NbConvertApp] Converting notebook GroversAlgorithm/GroversAlgorithm.ipynb to markdown
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS6307 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Not all code paths return a value.
      
---
[NbConvertApp] Converting notebook Teleportation/Teleportation.ipynb to markdown
[NbConvertApp] Writing 13087 bytes to Teleportation/Teleportation.md
Prebuilding: ComplexArithmetic.ipynb in tutorials/ComplexArithmetic kata...
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
**MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.**      

---
[NbConvertApp] Converting notebook tutorials/ExploringDeutschJozsaAlgorithm/DeutschJozsaAlgorithmTutorial.ipynb to markdown
**fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS6307 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Not all code paths return a value.**

---
[NbConvertApp] Converting notebook tutorials/ExploringGroversAlgorithm/ExploringGroversAlgorithmTutorial.ipynb to markdown
```
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3214 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Expecting initializer expression. Possibleinitializers are "Qubit()", "Qubit[expr]", or tuples thereof.
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3112 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Expecting assignment ("=").
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3203 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Invalid symbol declaration. Expecting either a single symbol or a symbol tuple.
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3101 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Syntax error in expression.
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3223 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Invalid argument. Expecting expression or missing argument indication ("_").
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3223 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Invalid argument. Expecting expression or missing argument indication ("_").
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3001 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Syntax does not match any known patterns.
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS3001 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Syntax does not match any known patterns.
```

---
[NbConvertApp] Writing 25083 bytes to tutorials/ExploringGroversAlgorithm/ExploringGroversAlgorithmTutorial.md
Prebuilding: LinearAlgebra.ipynb in tutorials/LinearAlgebra kata...
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
**MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.**

---
[NbConvertApp] Writing 55660 bytes to tutorials/MultiQubitSystems/MultiQubitSystems.md
Prebuilding: Qubit.ipynb in tutorials/Qubit kata...
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
**MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.**
[NbConvertApp] Converting notebook tutorials/Qubit/Qubit.ipynb to markdown

---
```
[NbConvertApp] Converting notebook tutorials/SingleQubitGates/SingleQubitGates.ipynb to markdown
Qubit in state |𝜓❭:
# wave function for qubits with ids (least to most significant): 0
∣0❭:     0.877583 +  0.000000 i  ==     ****************     [ 0.770151 ]     --- [  0.00000 rad ]
∣1❭:     0.479426 +  0.000000 i  ==     *****                [ 0.229849 ]     --- [  0.00000 rad ]
Qubit in state X|𝜓❭:
# wave function for qubits with ids (least to most significant): 0
∣0❭:     0.479426 +  0.000000 i  ==     *****                [ 0.229849 ]     --- [  0.00000 rad ]
∣1❭:     0.877583 +  0.000000 i  ==     ****************     [ 0.770151 ]     --- [  0.00000 rad ]
Qubit in state ZX|𝜓❭:
# wave function for qubits with ids (least to most significant): 0
∣0❭:     0.479426 +  0.000000 i  ==     *****                [ 0.229849 ]     --- [  0.00000 rad ]
∣1❭:    -0.877583 +  0.000000 i  ==     ****************     [ 0.770151 ] ---     [  3.14159 rad ]
Qubit in state YZX|𝜓❭:
# wave function for qubits with ids (least to most significant): 0
∣0❭:     0.000000 +  0.877583 i  ==     ****************     [ 0.770151 ]    ↑    [  1.57080 rad ]
∣1❭:     0.000000 +  0.479426 i  ==     *****                [ 0.229849 ]    ↑    [  1.57080 rad ]


**[NbConvertApp] ERROR | unhandled iopub msg: render_execution_path**
```

---
[NbConvertApp] Converting notebook tutorials/SingleQubitSystemMeasurements/SingleQubitSystemMeasurements.ipynb to markdown
fail: Microsoft.Quantum.IQSharp.Snippets[0]
      QS6307 (/snippet_.qs:Microsoft.VisualStudio.LanguageServer.Protocol.Range): Not all code paths return a value.

---
[NbConvertApp] Writing 31161 bytes to tutorials/SingleQubitSystemMeasurements/SingleQubitSystemMeasurements.md
Removing intermediate container 1531ba66e3e2
 ---> 0afcf96c7b4c
Step 8/9 : WORKDIR ${HOME}
 ---> Running in 67debcb6c9fa
Removing intermediate container 67debcb6c9fa
 ---> 12957ddcef9c
Step 9/9 : CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0"]
 ---> Running in 95de5ee55f2f
Removing intermediate container 95de5ee55f2f
 ---> b6b9c8f4f331
**{"aux": {"ID": "sha256:b6b9c8f4f3313b96c801fac43d09fad6da184693f6c523bbda1c50bb7379222e"}}[Warning] One or more build-args [NB_UID NB_USER] were not consumed**
Successfully built b6b9c8f4f331
Successfully tagged 3i2li627.gra7.container-registry.ovh.net/binder/ovhbhub-microsoft-2dquantumkatas-5a146c:72fbc953c3a968c27a71a4cfa32cdf4bd5dc6618

**Comment by cgranade** [comment]
I'm a bit confused why `Microsoft.VisualStudio.LanguageServer.Protocol.Range` didn't show up in earlier validations, but other than that, I'm not sure that any of the above failure should prevent the image build from working — they all look at most to affect whether specific projects are pre-built for first-run performance?

**Comment by tcNickolas** [comment]
Closing, as it is superseded by https://github.com/microsoft/QuantumKatas/pull/657.

**Pull request closed without merging**
