### PR TITLE
Switch to QDK ver 0.27.244707.

### PR DESCRIPTION
**Pull request by kuzminrobin**
https://mybinder.org/v2/gh/Microsoft/QuantumKatas/kuzminrobin/nov2022release?urlpath=/tree/index.ipynb
Looks like there are some temp issues at the mybinder.org side. I have seen such an error couple of days ago and re-clicking the link helped. But this time re-clicking does not help. I'll try to open the link after some time later today. 

The error:
Container engine initialization error: ('Check if docker is running on the host.', DockerException("Error while fetching server API version: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)"))

### CODE REVIEW

**Review by tcNickolas — APPROVED** [review]
The changes look good to me. However, the error on binder persists, though slightly different: `Container engine initialization error: ('Check if docker is running on the host.', DockerException("Error while fetching server API version: ('Connection aborted.', BlockingIOError(11, 'Resource temporarily unavailable'))"))`

Let's wait until we can build the preview from the branch before we merge this change. Currently the main branch of the repo is built and cached on Binder, so users can still use it, I don't want to jeopardize that by updating the branch when build is not possible.

If this persists, we might have to follow up at https://discourse.jupyter.org - several threads with similar error don't offer a solution.

**Comment by kuzminrobin** [comment]
Hmm... Friday night the link succeeded for me. Took tens of minutes to open... And now fails again :-) with the same message as you provided... I'll wait before merging...

**Comment by kuzminrobin** [comment]
After clicking again looks like the process started from the very beginning...

**Comment by kuzminrobin** [comment]
Now the link works. Merging.

**Comment by tcNickolas** [comment]
Did you kick off the Binder build on main after you merged the PR? It's not built right now

**Comment by kuzminrobin** [comment]
> Did you kick off the Binder build on main after you merged the PR? It's not built right now

I didn't know that I need to. Now I have kicked off for main.
I will update the release driver instructions.

**Comment by kuzminrobin** [comment]
It works for main now. I consider this PR fully complete.
Thank you @tcNickolas!

**Pull request merged**
