### PR TITLE
adding QFT workbook

### PR DESCRIPTION
**Pull request by WaywardPhoton**
Adding a workbook for the QFT

### CODE REVIEW

**Review by tcNickolas — CHANGES_REQUESTED** [review]
I took a quick look - overall looks very solid, just needs a round of final polish. I started the polish, but I only had time for tasks 1.1-1.3 today - I pushed those into the branch so that we're at the same page. (I've also cleared the cell execution results, which is why it looks like a lot more edits than I did!)

I'll continue it tomorrow afternoon (PST). Meanwhile, if you have a bit of time to do some edits, here are two things:
* We need to add links to and from the QFT kata itself after each code cell; I've added them to the first three tasks already.
* In task 1.6, the circuit diagrams don't really render well in ASCII... In other places we've used [Quirk](https://algassert.com/quirk) to draw circuits, but it doesn't allow to label the wires the way we want it to. Maybe we should just do a text description instead? Since our input and output are already given as text, this should remove the extra steps of converting that to a circuit and back to text again.

Thank you!

**Comment by WaywardPhoton** [comment]
I'm not able to pull the changes you made on the branch, and I'm not sure
why. I'm having a ton of trouble with this (I've never really used git
before). It might take me a while until  I get someone to help me.

**Comment by tcNickolas** [comment]
No worries, I'll take care of that tomorrow then!

**Comment by WaywardPhoton** [comment]
I want to add some nice schematics (I made them in Inkscape) to the
workbook. I'll get it done as soon as I figure out my git issue.

**Comment by tcNickolas** [comment]
I've found that often the easiest way to handle the git issues is to create a completely new clone of the repo. Especially in this case, since you need to do changes on top of the branch that exists in the remote repo.

Let me finish the polish round now, and I'll let you know when I'm done with the branch so that you can pull it and add the pictures on top of my changes.

**Comment by tcNickolas** [comment]
I finished the edits I had in mind! Caught a couple of embarrassing typos in the QFT kata itself in the process, so really happy we took the time to write the workbook - it always forces to give another careful look at the kata :-)

The only thing missing are the images (I left task 1.6 alone, since I'm not sure whether you have an image for it as well as for the 1.7). `obj` folder is ignored by git (typically it is only build artifacts), so we put images in the `img` folder ([Superposition kata](https://github.com/microsoft/QuantumKatas/tree/main/Superposition) is a good example).

**Comment by tcNickolas** [comment]
Aha, I finally figured out why the CI build checks didn't trigger - the target branch for the PR has to be main, not master (master is sort of hanging out there for backwards compatibility).

**Comment by tcNickolas** [comment]
If creating a separate clone of the https://github.com/WaywardPhoton/QuantumKatas repo and checking out the fix-QFT-wkbk branch doesn't work for getting the latest version of the branch that you can work with, you can just attach the images to this thread and I'll add them on my end. Let me know!

**Comment by WaywardPhoton** [comment]
I just can't seem to pull from the "fix-qft-wkbk" branch. I'll see if I can
get some help and if not, I will just upload the photos.

**Comment by tcNickolas** [comment]
What happens if you try to do the pull? Could the branch name be case-sensitive? Did your local version of the branch diverge from the one in the remote repo?

**Comment by WaywardPhoton** [comment]
Nothing happens when I do the pull. It says the branch is updated already
and nothing updates in my folder.
I can work with github in a basic capacity but the branching is beyond me.

**Comment by WaywardPhoton** [comment]
I figured it out... All the images are now updated in the fix-QFT-wkbk
branch. They are in the images folder. I'm not sure why they don't appear
in the jupyter notebook on GitHub but they do show up when I download it
and open it in the browser window. Basically, there should be 3 images for
1.6 and 1 image for 1.7.
Hopefully these are good. Sorry for the delay!


Ana

**Comment by tcNickolas** [comment]
I'm not sure these commits did exactly what we intended them to do... I see the images now, but my changes for the tasks after 1.4 are gone.

**Comment by WaywardPhoton** [comment]
I don't know what happened. Your original changes are in the master branch
still, so it is possible to salvage it. I can try and fix it.

**Comment by tcNickolas** [comment]
I think the easiest thing to do is to get the versions of both the kata and the workbook notebooks from 45b44e2, copy the pieces where you link to the images to them, and overwrite them on top of the notebooks from 8511636 (manually, so it would be a new commit). This should also fix the build failures we see in CI now (there were some open statements missing which cause the workbook validations to fail).

Give it a try and let me know how it goes; in the worst case, I can do it on my end :-)

**Comment by WaywardPhoton** [comment]
I think I fixed it. Your changes are shown, and now the images are also
there. The update is in the master branch because I couldn't figure out how
to merge it.

I'm sorry about that!

**Comment by tcNickolas** [comment]
Can you open a separate pull request from that branch? https://github.com/microsoft/QuantumKatas/compare/main...WaywardPhoton:master?expand=1 looks like it should do the trick, at a glance it has the right files and changes in them

**Comment by WaywardPhoton** [comment]
Done. New pull request, master --> master

**Comment by tcNickolas** [comment]
Closing this PR, as the latest work on the same is in https://github.com/microsoft/QuantumKatas/pull/636.

**Pull request closed without merging**
