### PR TITLE
[ExploringGroversAlgorithm] Covered Issues mentioned in #328

### PR DESCRIPTION
**Pull request by jainvasu631**
This is the last remaining part of Issue #328. I covered MultiQubitGates in Pull Request #375 , @anpfeife covered ExploringDeutschJoszaAlgorithm in Pull Request #443. Only ExploringGroversAlgorithm tutorial was left. 

I have added some heavy math in order to justify my explanations for last 3 cases. I also wanted to add this math earlier but was unsure of the best way to do so. The terse parts are hidden by default and if the reader is interested they can go through it.

Mostly I have based my explanations on my answer [here](https://quantumcomputing.stackexchange.com/questions/9978/changing-qubits-coefficients-to-trigonometric-functions-in-grover-algorithm/13150#13150) and the question I asked [here](https://quantumcomputing.stackexchange.com/questions/12790/grovers-algorithm-on-a-database-with-more-than-50-matching-entries).

### CODE REVIEW

**Review by tcNickolas — CHANGES_REQUESTED** [review]
I like the rigorousness of the math - I think about Grover's search algorithm analysis in terms of visual representation myself, so it's a nice compliment to that approach. However, I'm concerned whether this will be accessible to our learners - the contrast between the hands-on approach in the previous sections of the tutorial and the dense math in this section is pretty stark, and the formulas are hard to read even for somebody who is very familiar with the formalism. I'm worried some readers will just drop the tutorial at this point without reaping the benefits.

I would suggest trying to make the math a bit more accessible without sacrificing the rigorousness:
* I'll add the visual variant of the explanation a bit later, similar to the visuals I used in the [new Microsoft Learn module](https://docs.microsoft.com/en-us/learn/modules/solve-graph-coloring-problems-grovers-search/5-grovers-algorithm). I already have the images, so you don't need to work on them yourself - I'll just wait for this change to be merged to avoid merge conflicts.
* Let's use |good⟩ and |bad⟩ state vectors to denote superposition of all solutions and all non-solutions, rather than Greek symbols - that makes it easier for the reader to keep track of which is which (and matches the notation I'll use in the visuals).
* I would use 𝜃 to denote half of the rotation angle, not the whole angle - this should reduce the number of fractions in the formulas (and again, it will match the visuals).
* I suspect some of the sin−1 should actually be arcsin? I prefer to use explicit trigonometric function name "arcsin", to avoid confusion between it and the fraction "1 divided by sin".
* The reader might not be familiar with the << notation, we can write the same thing in words.
* Similarly, I would not use symbol ∀ - it is easily replaced by words, and it's harder to read (I think I last used it in shorthand for math lectures back in university, which didn't aim for general readability)

Let's start with these changes, and I'll try to think of other ways to make this material more readable while keeping it accurate.

Thank you!

**Comment by jainvasu631** [comment]
I will get on this.  I am bit busy during the weekdays. So I will probably work on this o'er the weekend.

**Comment by jainvasu631** [comment]
I have done the suggested changes.

Personally I always found visual explanations bordering on voodoo maths and preferred the cold mathematical rigor. 
However I do agree that this can be challenging to a novice. While I was fixing the changes, I myself was a bit taken aback at the terseness of the arguments. 
You are right about the lack of usage of the symbols  ∀ and << outside the university and college studies. Since I am currently in uni, I am used to cranking out proofs based on induction and formal logic statements and hence in the habit of using these symbols. However anyone outside of academics would find them quite alien. 

The half angle change does reduce the number of fractions but now every iteration of Grovers increases it proximity by 2 theta instead of theta when we did the maths in terms of half angles.

**Review by tcNickolas — APPROVED** [review]
First of all, I'm really sorry it took me so long to get back to this review! Oddly enough, I've never done the math to prove this formula, so it took me quite a bit of uninterrupted focus to go through it - and I haven't had that kind of focus time in quite a while.

This is great work, though! I did some minor edits, catching a couple of typos and making some formulas more readable, as well as rearranging the cells to make them easier to edit.

Thank you so much for doing this! And again, apologies for the delay.

**Pull request merged**
