### PR TITLE
Fix typo in MultiQubitSystemMeasurements.ipynb

### PR DESCRIPTION
**Pull request by delight1019**
Hello!

I fixed a typo in MultiQubitSystemMeasurements.ipynb.

### CODE REVIEW

**Review by tcNickolas — APPROVED** [review]
Thank you!

**Review by tcNickolas — CHANGES_REQUESTED** [review]
I just realized that the workbook for task 7 has the same issue, since task descriptions are duplicated in both notebooks. Can you do the same fix there as part of this pull request? (This is your 4th one so you shouldn't need a separate one for Hacktoberfest :-))

**Comment by delight1019** [comment]
> @delight1019 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by delight1019** [comment]
> I just realized that the workbook for task 7 has the same issue, since task descriptions are duplicated in both notebooks. Can you do the same fix there as part of this pull request? (This is your 4th one so you shouldn't need a separate one for Hacktoberfest :-))

Oops, I missed the workbook :( Thank you!!

**Review by tcNickolas — APPROVED** [review]
Thank you!

**Pull request merged**
