### PR TITLE
[SolveSATWithGrover] Kata Workbook

### PR DESCRIPTION
**Pull request by jainvasu631**
This is complete Kata Workbook for SolveSATWithGrover Kata. This is one of last remaining Katas mentioned in Issue #208 which havent yet been created. 

I am having some issue getting the CI Build to not fail.

### CODE REVIEW

**Comment by tcNickolas** [comment]
Thank you for working on this! Sorry I'm not very responsive to your PRs and questions, I'm totally swamped this week with the http://aka.ms/aqdw prep and a couple other things :-( But I hope to get back to reviews next week. 

I also have a refresh of the "help wanted" issues in mind (you've almost finished #208 in its current form already!) which I'll probably do closer to end of July or in early August.

**Comment by jainvasu631** [comment]
No worries @tcNickolas . I slowed down on the #208 because I felt I was almost spamming you on the Repository Pull Requests page. Then I saw that UnitaryPatterns Workbook got merged and hence figured you might be more free now.  No worries, you can review them whenever you get time. I am in no rush. 
Meanwhile, It will probably take me 2-3 days to get through this Workbook.

**Comment by jainvasu631** [comment]
@tcNickolas I am almost done with this Workbook. I have written the solutions and the code. However while running the `validate-notebooks.ps1` script I keep getting timeout error.
```
PS C:\Users\Dell\Desktop\QuantumKatas\SolveSATWithGrover> ..\scripts\validate-notebooks.ps1 .\Workbook_SolveSATWithGrover.ipynb
Setting up build environment variables

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       16/07/2020     01:26                nugets
Installing IQ# tool.
Tool path 'C:\Users\Dell\Desktop\QuantumKatas\scripts\.tools' does not exist.
Installing Microsoft.Quantum.IQSharp at C:\Users\Dell\Desktop\QuantumKatas\scripts\.tools
You can invoke the tool using the following command: dotnet-iqsharp
Tool 'microsoft.quantum.iqsharp' (version '0.12.20070124') was successfully installed.
[InstallKernelSpec] Installed kernelspec iqsharp in C:\Users\Dell\AppData\Roaming\jupyter\kernels\iqsharp
iq# kernel installed (0)
Checking notebook C:\Users\Dell\Desktop\QuantumKatas\SolveSATWithGrover\Workbook_SolveSATWithGrover.ipynb.
[NbConvertApp] Converting notebook Check.ipynb to html
Microsoft.Quantum.IQSharp.Jupyter, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Simulation.Common, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Standard, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.IQSharp.AzureClient, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Runtime.Core, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
Microsoft.Quantum.QSharp.Core, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Simulation.QCTraceSimulatorRuntime, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
Microsoft.Quantum.Simulators, Version=0.12.0.0, Culture=neutral, PublicKeyToken=40866b40fd95c7f5
[NbConvertApp] Executing notebook with kernel: iqsharp

[NbConvertApp] ERROR | Timeout waiting for execute reply (120s).

Traceback (most recent call last):
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\jupyter_core\application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\exporters\html.py", line 95, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\exporters\templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\exporters\exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\exporters\exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\preprocessors\execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\preprocessors\base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\preprocessors\execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\preprocessors\execute.py", line 571, in run_cell
    if self._passed_deadline(deadline):
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconve
rt\preprocessors\execute.py", line 541, in _passed_deadline
    self._handle_timeout()
  File "c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\nbconvert\preprocessors\execute.py", line 504, in _handle_timeout
    raise TimeoutError("Cell execution timed out")
TimeoutError: Cell execution timed out

##vso[task.logissue type=error;]Validation errors for C:\Users\Dell\Desktop\QuantumKatas\SolveSATWithGrover\Workbook_SolveSATWithGrover.ipynb .
##vso[task.logissue type=error;]Validation errors for Jupyter notebooks.
At least one test failed execution. Check the logs.
At C:\Users\Dell\Desktop\QuantumKatas\scripts\validate-notebooks.ps1:113 char:5
+     throw "At least one test failed execution. Check the logs."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (At least one te...Check the logs.:String) [], RuntimeException
    + FullyQualifiedErrorId : At least one test failed execution. Check the logs.
``` 

The script specifies a timeout of 120s. I think this limit maybe too short. Any ideas on how to fix it.
Manually running all cells in `Jupyter` gives success results and hence I am not sure what is causing the timeout.

**Comment by tcNickolas** [comment]
Yes, I believe this is the case, the notebooks are excluded from validation based on their individual names, not folder names, so a workbook would be prone to the same timeout issue that we encountered with the kata itself. Adding the workbook to the exceptions list should fix that.

Ideally we should modify the logic of the exceptions to be more fine-grained - as far as I recall, only a few tasks per notebook have this issue, so it should be possible to modify the validation script to skip only those tasks affected. But let me think about this separately, we shouldn't rush into doing this here.

**Comment by jainvasu631** [comment]
Okay. I'll add it to the exception list.

**Comment by jainvasu631** [comment]
Thanks for the review. 

I agree with you that solution for Task 1.4 is more complicated than it needs be. 
I initially wrote it such that the XOR of adjacent bits were stored in an ancillary array and then the solution was simply the AND of qubits of this ancillary array in the same manner as Task 1.1.

I later realised I could store the result of the XOR in the original register itself thereby avoiding the need for an ancillary register. However doing so required using the CNOT gates in a particular order which is what that complicated Product of Gates term reflects. Perhaps doing so was (for the lack of a better term) - was too *clever* and made the solution difficult to understand.

I think if I rewrite 1.4 by using a temporary ancillary array and dropping the notation intensive math, the solution would be more readable and beginner-friendly. 

Task 1.5 and perhaps other tasks as well:
I actually tried to make an effort to use more library utility functions and newer Q# constructs in the code in order to introduce them to the reader. I might have used them more than what was necessary. This was exacerbated by the fact that I didn't explain all those *neat* one-liners. These were intended to be syntactic sugar but turned out to be hard-to-read code.

I have 2 options to remedy this:
1. Rewrite the portions using simpler and familiar Q# constructs.
2. Explain the functions I have used using comments and explanations in the jupyter cells. 

Which do you think is a better idea?

**Comment by tcNickolas** [comment]
For 1.4, I think it's good to show both approaches - allocating ancillas is a more general reversible-computing way and easier to explain, computing XORs in place is a clever trick that is good to teach, it's just hard to get it behind all the math. I think you can do both, and just rewrite the math for in-place approach to be less scary :-)

For 1.5, I think it's better to use simpler Q# constructs... I prefer to use libraries when they offer a lot of advantage without the loss of readability, and not to chain them together. And again, you have the option to do both approaches, doing one with simpler code and the second one with some extras thrown in (with explanations), so that the learner can benefit from whichever approach they find more educational (or from both!)

**Comment by jainvasu631** [comment]
> For 1.4, I think it's good to show both approaches - allocating ancillas is a more general reversible-computing way and easier to explain, computing XORs in place is a clever trick that is good to teach, it's just hard to get it behind all the math. I think you can do both, and just rewrite the math for in-place approach to be less scary :-)
> 
> For 1.5, I think it's better to use simpler Q# constructs... I prefer to use libraries when they offer a lot of advantage without the loss of readability, and not to chain them together. And again, you have the option to do both approaches, doing one with simpler code and the second one with some extras thrown in (with explanations), so that the learner can benefit from whichever approach they find more educational (or from both!)

I tried rewriting the 1.5 one-liner using simpler Q# constructs as shown below.
```
// Find all qubits which are variables in clause
mutable clause_qubits = new Qubit[0];
for((index, positive) in clause) {
     set clause_qubits += [queryRegister[index]];
}
Oracle_Or(clause_qubits,target); // Disjuction of variables in clause.
```

However the problem with this is that using `mutable` and `set` means that `Adjoint` of the operations aren't created automatically and I couldn't find any way to write the simpler version without those. Hence the best simplification I could reach was to write the following 
```
let indexList = Mapped(Fst,clause); // Get Location of all variables in clause
let clause_qubits = Subarray(indexList,queryRegister); // Find all qubits which are part of clause
Oracle_Or(clause_qubits,target); // Disjuction of variables in clause.
``` 

I could manually write the `Adjoint` version of the code but I think that would make the operation too cumbersome.
Please tell me if you have any ideas ?

**Comment by tcNickolas** [comment]
My best attempt at this problem is in ReferenceImplementation.qs - we can define a function that would perform the necessary classical manipulations on mutable variables (including collecting necessary qubits in an array), and call it from the operation; this allows Adjoint to be generated automatically, and has a nice side benefit of illustrating a logical distinction between classical and quantum logic.

**Comment by jainvasu631** [comment]
@tcNickolas I have made the changes. The remaing tasks were not mathematically intense in terms of notations. There is some notation in Task 2.1 but I thought that is understandable. I have made the corresponding changes in Task 2.2 (in same vien as Task 1.5)
I have mentioned both versions in Task 1.5 in order to introduce the new library functions to the reader.

**Review by tcNickolas — APPROVED** [review]
I finally got to finishing this review, sorry for the delay! 

Looks good, the rewrite of the math made the solutions a lot more readable. I did a round of cleanup for formatting and the right framing of the workbook cells (for example, if we're offering an alternative solution to the task, it will have the same signature as the first one and the same test invocation - since it's a notebook, different cells with the same signature don't conflict with each other like they would in a Q# project).

I'll merge this once the CI passes. Thank you!

**Pull request merged**
