### PR TITLE
[UnitaryPatterns] Workbook Solutions Complete

### PR DESCRIPTION
**Pull request by jainvasu631**
Added Workbook_UnitaryPatterns and cross-linked it with UnitaryPatterns as discussed in [Comment in Issue #208](https://github.com/microsoft/QuantumKatas/issues/208#issuecomment-643804455).

The Workbook Solutions for all Tasks from 1 to 15 have been done. 
I didn't notice the solutions in ReferenceImplementation.qs hence I have implemented my own solutions for the most part. They are mostly similar to the ReferenceImplementations.
For Task 13 - Removed Encapsulated Functions since that was causing errors in the Kernel Cell
For Task 14 - The Solution is longer but I believe it is easier to comprehend that the reference solution.
For Task 15 - I have simplified the solution. The reference solution didn't take advantage of the fact that both indices are always consecutive.

All checks are now passing.

### CODE REVIEW

**Comment by manav28** [comment]
https://github.com/microsoft/QuantumKatas/issues/208#issuecomment-643530753

**Comment by tcNickolas** [comment]
Could you please unentangle this PR from the MultiQubitGates change in https://github.com/microsoft/QuantumKatas/pull/375? Looks like you've branched this PR off that branch, and I'd prefer to review them separately, since they are independent changes.

**Comment by jainvasu631** [comment]
Apologies. I didnt realise those changes got entangled with this Branch. I have reset the file to MultiQubitGates.ipynb as it is on the latest commit in Microsoft/QuantumKatas

**Comment by tcNickolas** [comment]
Looking at your initial comment, what do you mean by "Encapsulated Functions" and what kinds of errors were they causing?

**Comment by jainvasu631** [comment]
While writing solutions for Task 13, I used the helper `operation Decrement` to refactor some code. However, since this name was used in `Reference Implementation.qs` I  kept getting errors. Finally I decided to not refactor the code and instead wrote the entire function in main body only. Hence I was probably referring to the fact that operations in `ReferenceImplementation.qs`  cause namespace conflicts.

**Pull request merged**
