### PR TITLE
Added Introductory PPT for Principles of Quantum Computing

### PR DESCRIPTION
**Pull request by RankJay**
Added an Introductory PPT including all the basic principles of Quantum Computing

### CODE REVIEW

**Comment by tcNickolas** [comment]
This looks interesting - are you using these slides for some kind of presentation? I found https://twitter.com/QPowerOfficial but it's not clear whether these slides are part of this initiative or not.

Unfortunately, these slides don't quite align with the goals of the Quantum Katas project - we aim to offer an "engineering" introduction to quantum computing, with heavy emphasis on defining the concepts and tools in a way that allows to use them for solving problems immediately, rather than an "overview" introduction. (Besides, there are several inaccuracies in the slides, starting with the definition of superposition - we don't say it's a state of 0 and 1 simultaneously, it's more accurate to say it's a state that is a combination of 0 and 1.) 

If you're interested in contributing to the Katas, I'll be happy to work with you to help you define a work item and implement it!

**Comment by RankJay** [comment]
Hello Mariia,
I apologize for this mistake, I wanted to contribute to this open source project and no, I am not a part of QPower Community, though I am a Microsoft Student Partner-Beta.

Can you help me define a work item and how can I contribute to this project.?

Thanks again,
Jay

**Comment by tcNickolas** [comment]
There is nothing to apologize for, I appreciate your enthusiasm! 

How comfortable with Q# and quantum computing do you have? 
* For beginners I usually suggest https://github.com/microsoft/QuantumKatas/issues/190 - it's nice because it doesn't require a lot of experience and allows to validate your Q# installation and build process, make sure you're comfortable with the pull request process etc. 
* If you have some experience, we have some issues labeled [help wanted](https://github.com/microsoft/QuantumKatas/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) that you can choose from. 
* If you're feeling ambitious you can tackle a whole topic from the [roadmap](https://github.com/microsoft/QuantumKatas/wiki/Roadmap).

Let me know if any of these look interesting!

**Comment by RankJay** [comment]
@tcNickolas 
Thank you so much for your guidance, out of the selected ones, I would like to contribute towards this topic in 'Roadmap' :
https://github.com/Microsoft/QuantumKatas/tree/master/Measurements
Also, I had gone through many documentation of Quantum Computing on docs.microsoft site, hence, I am very much familiar with Quantum Computing,

But I would like to post a query that in this tutorial portion, do I have to add a new .ipynb file or do I have to update the document that is .md file?

**Comment by vivanwin** [comment]
Hi @RankJay,
I think you want to create a new folder with the tutorial content, both .md and .ipynb file. Take a look at the Qubit tutorial [here](https://github.com/microsoft/QuantumKatas/tree/master/tutorials/Qubit), that shows the structure of a tutorial.

Good luck!

**Comment by tcNickolas** [comment]
Hi @RankJay,

This is a great choice of topic! (but ambitious :-))

@vivanwin is right, tutorials are different from the katas (as you can see with the example of BasicGates kata and the corresponding tutorials SingleQubitGates and MultiQubitGates) and reside in a separate folder (in this case it would be tutorials/Measurements), together with the testing harnesses. But it's just the Notebook file, there's no .md version.

Here are some main points I think need to be reflected in the Measurements tutorial eventually:

**Part 1. Measuring single-qubit systems**

* Measuring a single qubit in computational basis, outcomes and their probabilities
* An exercise to calculate the probability of getting a specific outcome when measuring a given state (something like 0.6|0⟩ + 0.8|1⟩). It's tricky to implement in Q# so we could do something similar to exercise 1 in MultiQubitSystems - a pen and paper exercise with an answer to check yourself under the cut.
* Measuring a single qubit in a different Pauli basis (using |+⟩, |-⟩ Pauli X basis as an example)
* A pen-and-paper exercise (similar to previous one)
* Expressing different types of measurements in Q#
* Using measurements to distinguish single-qubit states
* Several exercises with different bases (similar to the first ones in the Measurements kata - finally some programming! :-))
* Representing measurements as projectors (in Dirac notation and in matrix notation)
* A note on non-observability of global phase

**Part 2. Measuring multi-qubit systems**

* Measuring all qubits in computational basis
* Programming exercise
* Partial measurements, probabilities of outcodes, system collapse (Dirac notation is going to work nicely here)
* Programming exercise
* Joint measurements of multiple qubits
* Programming exercise

Hmm, now that I started thinking more about it, this is a lot of content! We might want to split this into two separate tutorials, similar to what we did to single-qubit and multi-qubit systems.

I hope you're not completely intimidated by this plan! Please feel free to start with a small subset of topics, the first few bullets of the first tutorial, and send them in for review - progressing in small increments is a lot more efficient than trying to tackle the whole thing at once.

**Comment by RankJay** [comment]
Hi @tcNickolas 
Thank you so much for explaining this timeline, I really appreciate this. I'll right away start with Part 1 i.e. for single-qubit systems, and update with small segments I will be working in.

Had to say,
@vivanwin and @tcNickolas 
You guys are really outstanding and just worth it, thanks for such amazing support.

**Comment by RankJay** [comment]
Hi @tcNickolas 
Sorry for bothering you again,

I had a question that how does this Measurements.ipynb file, I will be drafting be different from the Measurement Kata's notebook file. What differences should be present in this new notebook and also is there similarities or inspiration, I can take from Measurements Kata as well ?

**Comment by vivanwin** [comment]
Hi @RankJay,

The Katas are mostly coding challenges, while the tutorials are more explanation with examples. 
For example: [this](https://github.com/microsoft/QuantumKatas/blob/master/tutorials/Qubit/Qubit.ipynb) Qubit tutorial, gives the learner some background on the problem and basic understanding on how a Qubit works. 
After a Qubit tutorial the learner should move to the [Single Qubit Gates](https://github.com/microsoft/QuantumKatas/blob/master/tutorials/SingleQubitGates/SingleQubitGates.ipynb) katas, where the knowledge from the tutorial can be used to solve te coding challenges.
My idea for the measurement tutorial would to create a something similar, where a new learner could use the measurement tutorial to get started with the subject, using the examples that @tcNickolas has pointed out above and then could use this knowledge in the measurement katas.
So you could use inspiration from both the measurement kata and the qubit tutorial.
Hope this helps.

**Comment by RankJay** [comment]
hi @vivanwin 
That's just great, this cleared my doubts up, thank you so much. Will start working towards it right away.

**Comment by RankJay** [comment]
hi @vivanwin and @tcNickolas,
I just added a basic introduction to the Measurement tutorial and sent a new PR with #360, can you please review it and update me about it, whether it is feasible or not?

**Pull request closed without merging**
