### PR TITLE
Task 1.8 V3!

### PR DESCRIPTION
**Pull request by TonyHoldroyd**
Task 1.8 V3! with that null thing but try again

### CODE REVIEW

**Comment by TonyHoldroyd** [comment]
Ciao Mariia,
I have had a few _draft_ pull requests which have given  strange problems but I finally managed to get just one Task, 1.8, passed the parser checks.  I don't want to tempt fate by closing this without you seeing it. It's quite short, but I  I have the rest of the tasks ready, say two at a time, when you have had a chance to look at this I'll append and create pull requests for them. Thanks.

**Review by tcNickolas — APPROVED** [review]
Looks great! I added a link from the kata to the new solution, and did a bit of cleanup. I removed the reference to the measurements, since at this point learners are not yet familiar with the concept, and I've heard often that encountering unfamiliar concepts is stressful. 
(We'll need to do a bit of work on the BasicGates kata in that vein, actually, since it switches from single-qubit systems and gates to multi-qubit ones without warning, and I got some feedback about that. But that's in the future!)

Thank you! (And apologies for the delay reviewing the PR - I was out last week, and busy with kicking off Q# Advent Calendar this week)

**Comment by TonyHoldroyd** [comment]
Thanks Mariia, We're on the road for a few days, travelling down to
southern Italy for the winter, I'll be submitting another pull request
after we have settled in. I have the solution ready.

**Comment by tcNickolas** [comment]
That sounds wonderful, especially the southern Italy part!

**Pull request merged**
