### PR TITLE
Added Tasks 1.8, 1.9, & 1.10 to BasicGates workbook

### PR DESCRIPTION
**Pull request by TonyHoldroyd**
Added Tasks 1.8, 1.9, & 1.10 to BasicGates workbook

### CODE REVIEW

**Comment by tcNickolas** [comment]
Could you check where the conflicts are coming from? Probably from a very similar place to the last pull request

**Comment by TonyHoldroyd** [comment]
Closeed due to conflicts

**Comment by tcNickolas** [comment]
One thing you can try is copy the workbook with the new tasks someplace safe, delete your repository and fork it from scratch. This way you get a clean slate for your main branch, to which you can do those changes incrementally, rather than carrying the whole 50-commit history on this. I know I sometimes get my repo clones to the point at which this is the easiest thing to do :-)

**Comment by TonyHoldroyd** [comment]
I must have read your mind, that's exactly what I did.
I'm also making much use of draft pull requests.

**Comment by TonyHoldroyd** [comment]
I had a few more weird problem messages so I worked on adding  just one
extra task with draft pull request task 1.8, , which now has passed the
parser! I have the rest of the tasks ready, I thought to add them maybe two
at a time.

**Pull request closed without merging**
